- name: Perform simple health checks to ensure web page is still running properly
  hosts: all
  tasks:
#    - wait_for:
#      timeout: 3
    - name: Accesing managed server 1 SampleWebApp
      uri:
        url: "http://192.168.1.112:7003/{{ appname | default('SampleWebApp') }}"
        method: GET
        return_content: yes
        status_code: 200

    - name: Accesing managed server 2 SampleWebApp
      uri:
        url: "http://192.168.1.112:7004/{{ appname | default('SampleWebApp') }}"
        method: GET
        return_content: yes
        status_code: 200