- name: Download artifact from Nexus to deployment folder
  hosts: all
  tasks:
    - name:                 Download artifact from Nexus
      maven_artifact:
        repository_url:     "http://nexus3-nexus-project.apps.cluster-a3e9.a3e9.sandbox567.opentlc.com/repository/releases/"
        group_id:           "com.redhat"
        artifact_id:        "{{ appname | default('SampleWebApp') }}"
        version:            "latest"
        extension:          "war"
        dest:               "/home/cytan/Downloads/SampleWebApp.war"
        mode:               '0755'
        verify_checksum:    always

#    - name:                 Update the war file permission
#      file:
#        path: "/home/cytan/Downloads/tmp/SampleWebApp.war"
#        mode: '0755'