- name: Undeploy an applicaiton
  hosts: all
  tasks:
    - name: Undeploying SampleWebApp to WebLogic Cluster wls_cluster_1
      command: "java -cp /home/cytan/Oracle/Middleware/Oracle_Home/wlserver/server/lib/weblogic.jar weblogic.Deployer -verbose -noexit -adminurl http://localhost:7001 -username {{ username | default('deployer') }} -password {{ password | default('weblogic1') }} -name {{ appname | default('SampleWebApp') }} -undeploy -timeout 300"
      register: output
      failed_when: "'failed' in output.stderr"

    - debug:
        var: output